# Generated by Django 2.1.5 on 2020-08-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclientes', '0002_auto_20200817_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'myclientes', 'verbose_name_plural': 'Clientes'},
        ),
    ]
