# Generated by Django 2.1.5 on 2020-08-18 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclientes', '0003_auto_20200817_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
    ]
